const body=document.body;const navToggle=document.querySelector('[data-nav-toggle]');const navMenu=document.querySelector('[data-primary-nav]');const themeToggle=document.querySelector('[data-theme-toggle]');const toast=document.querySelector('[data-toast]');const STORAGE_KEY='px-theme';const prefersDark=window.matchMedia('(prefers-color-scheme: dark)');
const applyTheme=(theme,{persist=true}={})=>{body.setAttribute('data-theme',theme);if(persist){localStorage.setItem(STORAGE_KEY,theme);}themeToggle?.setAttribute('aria-pressed',theme==='dark')};
const storedTheme=localStorage.getItem(STORAGE_KEY);if(storedTheme){applyTheme(storedTheme);}else{applyTheme(prefersDark.matches?'dark':'light',{persist:false});}
prefersDark.addEventListener('change',event=>{if(!localStorage.getItem(STORAGE_KEY))applyTheme(event.matches?'dark':'light',{persist:false})});
navToggle?.addEventListener('click',()=>{const isExpanded=navToggle.getAttribute('aria-expanded')==='true';navToggle.setAttribute('aria-expanded',String(!isExpanded));navMenu?.setAttribute('data-open',String(!isExpanded))});
navMenu?.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{if(window.innerWidth<992){navToggle?.setAttribute('aria-expanded','false');navMenu?.setAttribute('data-open','false')}}));
const currentPath=window.location.pathname.split('/').pop()||'index.html';const aliasMap={"athlete.html":"athletes.html"};const current=aliasMap[currentPath]||currentPath;document.querySelectorAll('[data-primary-nav] .nav-link').forEach(link=>{const href=link.getAttribute('href');if(href===current||(href==='index.html'&&current===''))link.classList.add('active')});
themeToggle?.addEventListener('click',()=>{const next=body.getAttribute('data-theme')==='dark'?'light':'dark';applyTheme(next,{persist:true})});
export const showToast=(message,type='info')=>{if(!toast)return;toast.textContent=message;toast.dataset.open='true';toast.setAttribute('data-type',type);clearTimeout(showToast._timeout);showToast._timeout=setTimeout(()=>{toast.dataset.open='false'},4000)};
window.addEventListener('keydown',evt=>{if(evt.key==='Escape'&&navMenu?.dataset.open==='true'){navToggle?.click()}});
